//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsWebBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsWebBrowser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept_yes.
        /// </summary>
        internal static string accept_yesDomId {
            get {
                return ResourceManager.GetString("accept_yesDomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data[name].
        /// </summary>
        internal static string articleNameDomId {
            get {
                return ResourceManager.GetString("articleNameDomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data[group_suggest_text].
        /// </summary>
        internal static string articleSuggestDomId {
            get {
                return ResourceManager.GetString("articleSuggestDomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checked.
        /// </summary>
        internal static string checkAttributName {
            get {
                return ResourceManager.GetString("checkAttributName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data[d_address].
        /// </summary>
        internal static string companyAddressElementDomId {
            get {
                return ResourceManager.GetString("companyAddressElementDomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data[d_company_name].
        /// </summary>
        internal static string companyNameDomId {
            get {
                return ResourceManager.GetString("companyNameDomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to currency_rsd.
        /// </summary>
        internal static string currencyRsdDomId {
            get {
                return ResourceManager.GetString("currencyRsdDomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data[condition]new.
        /// </summary>
        internal static string dataDomId {
            get {
                return ResourceManager.GetString("dataDomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data[description].
        /// </summary>
        internal static string descriptionDomId {
            get {
                return ResourceManager.GetString("descriptionDomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data[ad_kind]goods.
        /// </summary>
        internal static string goodsDomId {
            get {
                return ResourceManager.GetString("goodsDomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iphone_afraid {
            get {
                object obj = ResourceManager.GetObject("iphone_afraid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price_number.
        /// </summary>
        internal static string priceNumberDomId {
            get {
                return ResourceManager.GetString("priceNumberDomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data[promo_type]none.
        /// </summary>
        internal static string promoTypeDomId {
            get {
                return ResourceManager.GetString("promoTypeDomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data[d_registration_number].
        /// </summary>
        internal static string registrationNumberDomId {
            get {
                return ResourceManager.GetString("registrationNumberDomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swear_yes.
        /// </summary>
        internal static string swear_yesDomId {
            get {
                return ResourceManager.GetString("swear_yesDomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string valueAttributName {
            get {
                return ResourceManager.GetString("valueAttributName", resourceCulture);
            }
        }
    }
}
